apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  replicas: 1
  template:
    metadata:
      name: producer
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: daoistw/producer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: CLICKSTREAM-DATA
              value: /app/resources/ClickStreamMasterData.csv
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              value: kafka:9092
      restartPolicy: Always
  selector:
    matchLabels:
      app: producer